# Generated by Django 5.2.7 on 2025-10-07 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("services", models.JSONField(default=list)),
                (
                    "staff",
                    models.ManyToManyField(
                        limit_choices_to={
                            "role__in": ["DOCTOR", "RECEPTIONIST", "ADMIN"]
                        },
                        related_name="clinics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
