# Generated by Django 5.2.7 on 2025-10-07 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("notes", models.TextField(blank=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("prescription", models.JSONField(default=list)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.appointment",
                    ),
                ),
            ],
        ),
    ]
