# Generated by Django 5.2.7 on 2025-10-07 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("CONFIRMED", "Confirmé"),
                            ("CANCELLED", "Annulé"),
                            ("COMPLETED", "Complété"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
    ]
